In [1]:
import numpy as np
import pandas as pd

# Source on Dataset

[Global Data on Sustainable Energy - Ansh Tanwar](https://www.kaggle.com/datasets/anshtanwar/global-data-on-sustainable-energy)

In [2]:
df = pd.read_csv("database/global-data-on-sustainable-energy.csv")

In [3]:
display(df)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [6]:
sampled_df = df.sample(n=500, random_state=42)

In [7]:
display(sampled_df)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
1406,Guinea,2019,42.200000,1.6,29.88,819800000.0,65.44,0.75,0.00,1.31,...,1201.7898,5.570000,3950.000048,NaN,5.646176,1058.143368,53,245857.0,9.945587,-9.696645
3598,Yemen,2012,52.410000,60.0,0.06,79630000.0,1.08,6.65,0.00,0.00,...,2769.0400,2.790347,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.00,5.46,...,3441.9858,9.830000,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3230,Tajikistan,2001,98.633100,40.0,642.72,NaN,64.07,0.17,0.00,14.06,...,9605.3660,9.840000,2150.000000,NaN,9.580836,171.048065,68,144100.0,38.861034,71.276093
3114,Spain,2011,100.000000,100.0,NaN,NaN,14.79,146.12,57.72,87.53,...,35901.0700,3.040000,274399.993900,15.473434,-0.814373,31636.446310,94,505370.0,40.463667,-3.749220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,Chile,2007,98.092020,100.0,327.89,93230000.0,30.46,33.69,NaN,22.29,...,22387.7800,3.810000,64569.999690,18.706137,4.905325,10502.350710,26,756096.0,-35.675147,-71.542969
2457,North Macedonia,2006,99.000000,63.1,NaN,NaN,19.80,5.36,0.00,1.65,...,15953.7170,5.170000,9220.000267,14.188615,5.137025,3362.968419,83,25713.0,41.608635,21.745275
1298,Germany,2016,100.000000,100.0,NaN,NaN,14.24,368.67,84.63,189.67,...,46675.7770,3.040000,747150.024400,14.607312,2.230000,42107.517270,240,357022.0,51.165691,10.451526
14,Afghanistan,2014,89.500000,26.1,8.95,6940000.0,18.93,0.16,0.00,1.00,...,868.5762,2.250000,4880.000114,NaN,2.724543,614.223342,60,652230.0,33.939110,67.709953
755,Colombia,2020,100.000000,93.2,266.33,NaN,NaN,27.17,0.00,49.97,...,10064.3890,NaN,NaN,30.772787,-6.795758,5334.556042,46,1138910.0,4.570868,-74.297333

In [11]:
sampled_df.isnull().sum()

Entity                                                                0
Year                                                                  0
Access to electricity (% of population)                               0
Access to clean fuels for cooking                                    22
Renewable-electricity-generating-capacity-per-capita                135
Financial flows to developing countries (US $)                      287
Renewable energy share in the total final energy consumption (%)     24
Electricity from fossil fuels (TWh)                                   3
Electricity from nuclear (TWh)                                       16
Electricity from renewables (TWh)                                     3
Low-carbon electricity (% electricity)                                9
Primary energy consumption per capita (kWh/person)                    0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)          24
Value_co2_emissions_kt_by_country                                    53
Renewables (% equivalent primary energy)                            292
gdp_growth                                                           43
gdp_per_capita                                                       38
Density\n(P/Km2)                                                      0
Land Area(Km2)                                                        0
Latitude                                                              0
Longitude                                                             0
dtype: int64

In [13]:
sampled_df.to_csv("database\\test_sample.csv")